version: '3.7'

services:
  conduit-server:
    environment:
      - POSTGRES_CONNECT_STRING=host=db port=5432 user=postgres password=postgres dbname=conduit connect_timeout=10
      - POSTGRES_POOL_SIZE=4
      - JWK_STRING=b3d3038c4f8c44589de316439d3d227c

  db:
    ports:
      - "8432:5432"
